//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingList.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingList
    {
        public int ShoppingListId { get; set; }
        public string ShoppingListName { get; set; }
        public string ShoppingListAuthor { get; set; }
    }
}
